#!/bin/bash --norc

ROOT="external/crosstool_ng_linux_x86_64_gcc_4.9.4"
PREFIX="x86_64-unknown-linux-gnu"
TOOL=$(basename $0)

export PATH=$ROOT/bin:$PATH

exec -a $PREFIX-$TOOL $ROOT/bin/$PREFIX-$TOOL "$@"
